// This file is auto-generated by scripts/sync-levels.mjs. Do not edit by hand.
import type { MiniSudokuLevel } from "./types";
import level1 from "./level1";
import level106 from "./level106";
import level107 from "./level107";
import level2 from "./level2";
import level3 from "./level3";
import level4 from "./level4";
import level5 from "./level5";

const generatedLevels: MiniSudokuLevel[] = [level1, level106, level107, level2, level3, level4, level5];

export default generatedLevels;
