import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";

const LEVEL_FILENAME_REGEX = /^level.+\.ts$/i;
const GENERATED_FILENAME = "generated-levels.ts";

const run = async () => {
  const levelsDir = path.join(process.cwd(), "src", "levels");
  const entries = await fs.readdir(levelsDir);

  const levelFiles = entries
    .filter((file) => LEVEL_FILENAME_REGEX.test(file))
    .sort((a, b) => a.localeCompare(b));

  if (levelFiles.length === 0) {
    console.warn("[levels] No level files found. Skipping sync.");
    return;
  }

  const importLines = levelFiles
    .map((file) => {
      const identifier = path.basename(file, ".ts");
      return `import ${identifier} from "./${identifier}";`;
    })
    .join("\n");

  const arrayEntries = levelFiles
    .map((file) => path.basename(file, ".ts"))
    .join(", ");

  const banner =
    "// This file is auto-generated by scripts/sync-levels.mjs. Do not edit by hand.";

  const fileContents = `${banner}
import type { MiniSudokuLevel } from "./types";
${importLines}

const generatedLevels: MiniSudokuLevel[] = [${arrayEntries}];

export default generatedLevels;
`;

  await fs.writeFile(
    path.join(levelsDir, GENERATED_FILENAME),
    fileContents,
    "utf8",
  );

  console.log(`[levels] Synced ${levelFiles.length} level(s).`);
};

run().catch((error) => {
  console.error("[levels] Failed to sync level manifest:", error);
  process.exitCode = 1;
});

